# Álgebra Lineal con Python

Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


In [2]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [3]:
# Vamosa genera 3 listas
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [4]:
# Que tipo de objeto es
type(L)

list

In [5]:
# Transformar listas a otros objetos
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [6]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [7]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [9]:
# Llamamos a la libreria para hacer operaciones vectoriales
import numpy as np

In [10]:
L_vector = np.array(L) # Convertir una lista en un vector. La función "np.array" es la que hace la transformación

L_vector

array([1, 2, 3, 4, 5])

In [11]:
type(L_vector)

numpy.ndarray

In [12]:
# Se hacen conversiones de listas a vectores
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [13]:
# Se ve el numero de elmentos que tiene cada vector
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

### Con esto ya podemos sumar vectores pero tienen que tener el mimso numero de elementos se pueden sumar.


In [14]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`




Un total de $30$ boletos fueron vendidos para un evento, sumando una recaudación total de $\$150$. Los boletos para adultos cuestan $\$7$, mientras que los boletos para niños cuestan $\$3$. ¿Cuántos boletos de cada tipo se vendieron?



Sea \(x\) el número de boletos para adultos vendidos y \(y\) el número de boletos para niños vendidos. Las condiciones del problema se traducen en el siguiente sistema de ecuaciones:



x + y = 30, \\
7x + 3y = 150.


Resolviendo el sistema:

De la primera ecuación, despejamos \(y\):

y = 30 - x.

Sustituimos en la segunda ecuación:

7x + 3(30 - x) = 150.


Simplificamos:

7x + 90 - 3x = 150  
4x + 90 = 150
4x = 60
x = 15.


Sustituyendo \(x = 15\) en \(y = 30 - x\):
\[
y = 30 - 15 = 15.
\]

Por lo tanto, el número de boletos vendidos fue:

x = 15

### vamos a resolver este problema usando NumPy

In [15]:
# Escribimos la matriz con el sistema de ecuaciones
A = np.array([1, 1, 7, 3]).reshape((2,2))
A

array([[1, 1],
       [7, 3]])

In [16]:
# Vector de sistema de ecuaciones
B = np.array([1,3])

$$AX=B$$

In [17]:
# la función solve resuelve el sistema de ecuaciones
X = np.linalg.solve(A,B)

X

array([0., 1.])

La solución de sistema de ecuaciones es de
X= 0
Y= 1